language: python
python:
  - 3.6
#sudo: enabled
addons:
  apt:
    packages:
    - xvfb
    - libfontconfig
    - wkhtmltopdf
install: ./setup-dist.sh
script: ./make-dist.sh
deploy:
  skip_cleanup: true